In [4]:
"""
Created on Tuesday Oct 20 19:49:16 2022

@author: Ahmet Sina Soykan
"""

import numpy as np                                                    #importing numpy library
import random                                                         #importing random library

for k in range(8):                                                    #creating 8 list named Loto_{k} with random samples (k=0,1,2,3,4,5,6,7)
    exec(f'Loto_{k} = random.sample(range(1,49),6)')

Array_Loto_0 = np. array(Loto_0)                                      #converting lists to the arrays
Array_Loto_1 = np. array(Loto_1)
Array_Loto_2 = np. array(Loto_2)
Array_Loto_3 = np. array(Loto_3)
Array_Loto_4 = np. array(Loto_4)
Array_Loto_5 = np. array(Loto_5)
Array_Loto_6 = np. array(Loto_6)
Array_Loto_7 = np. array(Loto_7)

Real_Loto= np.concatenate((Array_Loto_0,Array_Loto_1,Array_Loto_2,    #Concatenate all arrays
                           Array_Loto_3,Array_Loto_4,Array_Loto_5,
                           Array_Loto_6,Array_Loto_7))

Soykan = Real_Loto.reshape(8,6)                                       #Making 8x6 Matris with concatenated arrays
print(Soykan)                                                         #Print reshaped array

[[ 5 37 41  2 16 42]
 [40 31 20 46 13 30]
 [27 24 40 23 21 22]
 [40 39  6 16 12 26]
 [47 33 13 27 41 18]
 [ 6 21 13 29 38 32]
 [40 32 18  1 38 24]
 [11 13  5 15 43  2]]
