In [2]:
"""
Created on Tuesday Oct 20 12:10:31 2022

@author: Ahmet Sina Soykan
"""

import numpy as np                                                    #importing numpy library
import random                                                         #importing random library

for k in range(6):                                                    #creating 6 list named Loto_{k} with random samples (k=0,1,2,3,4,5)
    exec(f'Loto_{k} = random.sample(range(45),8)')

Array_Loto_0 = np. array(Loto_0)                                      #converting lists to the arrays
Array_Loto_1 = np. array(Loto_1)
Array_Loto_2 = np. array(Loto_2)
Array_Loto_3 = np. array(Loto_3)
Array_Loto_4 = np. array(Loto_4)
Array_Loto_5 = np. array(Loto_5)

Real_Loto= np.concatenate((Array_Loto_0,Array_Loto_1,Array_Loto_2,    #Concatenate all arrays
                           Array_Loto_3,Array_Loto_4,Array_Loto_5))

Soykan = Real_Loto.reshape(6,8)                                       #Making 6x8 Matris with concatenated arrays
print(Soykan)                                                         #Print reshaped array

[[16 29 36 10 27 37 23 15]
 [20 23  7 32 36 16 25 24]
 [14 43 34 11 23  5 24 30]
 [21  3 19 38 18 32 36 26]
 [21 35 17 33  0 12 43 24]
 [33 30 31 41 36 19 39 29]]
